### ISSUE TITLE
Cant connect NODEMCU

### ISSUE THREAD

**Issue by JorgeLiberato** [nathanRamaNoodles/Tinker-Controller#1]
Greetings, Nathan.

I'm trying to use your project to connect my xbox one controller to my Nodemcu Esp12E. I upload your "Tinker_Controller_WIFI.ino" to my board and everything looks fine. The wireless network is created, my phone connect to it, the serial monitor displays the IP address, etc. But when i try to send commands with my controller, nothings happens. I've tried to use an UDP-sender app to verify but nothing happens at all.

Can you help me? Im trying to make an RC tank.

Regards.

**Comment by nathanRamaNoodles** [comment]
Is the esp12E's WiFiUDP.h library updated? You can do this by updating esp8266 in your board's manager.  Also, how did you test it?  
On a side note, I have code written for a moving vehicle similar to your tank:  [Tinker Car](https://github.com/nathanRamaNoodles/Tinker-Controller/tree/master/Arduino/Projects/Tinker%20Car)

**Comment by JorgeLiberato** [comment]
Well, i think it is up to date. This library is not installed like the most. To install, i have to add an link to the tab "preferences" and then add the board in board manager. Im using version 2.5.2 of esp8266 by ESP8266 Community. 

Im testing following your steps on the README.md file. I have downloaded your demo.apk, i connect my xbox controller to my phone (moto Z play android 8.0). I can see the buttons animation on the app as i move in the controller. I just cant send this to the nodemcu. 

Thanks for your help.

**Comment by nathanRamaNoodles** [comment]
That's very strange.  I have esp8266 software v2.5.2 and running it on my Wemos D1 mini, yet it works for me.  Hmm.
Maybe try adding `yield()` after every case and before every break.  For instance: 
Change this:
```
case 'a':
      switch (value) {  //use switch statements if you aren't printing to Serial.
        case 1:
          Serial.println("A on");
          digitalWrite(LED, LOW);
          break;
        case 0:
          Serial.println("A off");
          digitalWrite(LED, HIGH);
          break;
      }
      break;
```
to this:
```
case 'a':
      yield();
      switch (value) {  //use switch statements if you aren't printing to Serial.
        case 1:
          Serial.println("A on");
          digitalWrite(LED, LOW);
          break;
        case 0:
          Serial.println("A off");
          digitalWrite(LED, HIGH);
          break;
      }
      yield();
      break;
```
**Edit: do this for all the cases**

**Comment by JorgeLiberato** [comment]
I cant receive packets yet, but now the nodemcu is resetting. I will copy the message below:

Configuring access point...AP IP address: 192.168.4.1
Port: 4210

 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v8b899c12
~ld

Configuring access point...AP IP address: 192.168.4.1
Port: 4210

**Comment by nathanRamaNoodles** [comment]
Oh, ok.  So don't add the extra `yield()`'s 
Let's try debugging this with [packetsender tool](https://packetsender.com/)
After installing it, make sure you enable Streaming mode for the ESP12E board by uncommenting
```
#define STREAMING
```
It's at [line 18](https://github.com/nathanRamaNoodles/Tinker-Controller/blob/master/Arduino/Basics/Tinker_Controller_WIFI/Tinker_Controller_WIFI.ino#L18)

1. Upload to ESP12E and then connect your computer to the ESPtest network.
2. Next, set the settings similar to mine
   + ![packetsender test](https://user-images.githubusercontent.com/32442782/59151162-ea271980-89f3-11e9-849f-d0f0682b02f8.PNG)
3. Send packets and you should definitely see something
4. When you're done debugging, comment `#define STREAMING`  and then upload to ESP12E.

**Comment by JorgeLiberato** [comment]
I really don't know what i did before... Now that i've tried this packetsender, IT WORKS! Thanks for your help, Nathan.

**Comment by JorgeLiberato** [comment]
Now im gonna do some config on these buttons and soon you will have news about my robot! Thanks a lot. And just to be honest: im brazilian. Im not the best in english, but thanks for your patience.

**Comment by nathanRamaNoodles** [comment]
Your English is pretty good. Also, I'm glad it's working now. Have fun!

**Comment by JorgeLiberato** [comment]
Nathan, hello! I'm trying to connect wirelessly my arduino mega 2560 to my xbox one controller. I'm using the USB Host Shield but they don't have the support for this controller. Since you've managed to decode the protocol to send the information about the buttons and analogs, i thought you could help me to create this script. 

Jorge.

**Comment by nathanRamaNoodles** [comment]
The actual decoding of the Bluetooth protocol is done by Android. My app simply takes the controller list provided by the android controller api. From there, I simply assigned each button to a command.  Cracking the Bluetooth protocol is pretty difficult and can only be done if there is a Bluetooth stack written for the microcontroller.  The esp32 is your best bet, but it's still a long shot(xbox controllers are usually annoying when pairing).

**Comment by JorgeLiberato** [comment]
Oh, I see. But can't you explain to me how the buttons are transmitted? So
I can try to transmit and receive via RF.

Thank, you!

Em qua, 18 de mar de 2020 15:23, Nathan Ramanathan <notifications@github.com>
escreveu:

**Comment by nathanRamaNoodles** [comment]
You can't transmit via RF to an xbox controller (we haven't cracked their wifi protocol).

My app transmits via UDP wifi packets. The digital buttons are sent with 2 characters.  And the analog buttons are sent with 4 characters. To increase speed, I made every analog packet the same size.  So moving the joystick a little would give `j005` or something, and then moving it a lot would give `j255`.  Keeping the same size for a udp packet increases speed on the android app(for some reason, idk tbh).

The esp8266 parsers the data by looking at the first character, and then converting the rest to digital numbers.  Converting a char array to ints is a simple "char subtraction and multiply by ten" thing I pulled from stackoverflow.com
