### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [nathanRamaNoodles/Tinker-Controller#3]
Hi,

Since this app is GNU GPL V3 licensed, are you considering the fact to add the android part to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by nathanRamaNoodles** [comment]
Sounds like a swell idea.  Though, I'd rather let someone other than me do that cause I'm working on other projects at the moment.  Plus it let's me hand over the reins to someone other than me. 

So, yes **you have my permission to host Tinker-Controller on F-Droid. ** As long as you point I'm the creator and add the license.

Thanks!
