### ISSUE TITLE
Random disconnects with app

### ISSUE THREAD

**Issue by mcloughlan** [nathanRamaNoodles/Tinker-Controller#8]
The app runs fine and detects the esp network, but it randomly disconnects after a few seconds.
Here is my log.
![image](https://user-images.githubusercontent.com/50229842/103161254-1a7f1480-4833-11eb-848f-ad86a993e178.png)

**Comment by nathanRamaNoodles** [comment]
Maybe the phone is reconnecting to your router when there is no internet on the esp8266?  What you can do is disable auto connect to your wifi router.

**Comment by mcloughlan** [comment]
> Maybe the phone is reconnecting to your router when there is no internet on the esp8266? What you can do is disable auto connect to your wifi router.

I factory reset the phone a while back so there isn't any previously connected networks

**Comment by nathanRamaNoodles** [comment]
check if it works again
